default: &default
  protocol: 'http'
  host: couchdb
  port: 5984
  username: admin
  password: password
  prefix: opendig

development:
  <<: *default
  suffix: development

test:
  <<: *default
  suffix: test
