name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:3.2.0-alpine

    services:
      couchdb:
        image: couchdb:3.4
        env:
          COUCHDB_USER: ${{ env.COUCHDB_USER }}
          COUCHDB_PASSWORD: ${{ env.COUCHDB_PASSWORD }}
        ports:
          - 5984:5984
        options: >-
          --health-cmd "curl -f http://localhost:5984/_up || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      RAILS_ENV: test
      COUCHDB_HOST: couchdb
      COUCHDB_PORT: 5984
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add --update --no-cache \
             build-base \
             ca-certificates \
             glib \
             libc-dev \
             libffi-dev \
             libgcc \
             libintl \
             libstdc++ \
             libx11 \
             libxext \
             libxml2-dev \
             libxrender \
             libxslt-dev \
             nodejs \
             pcre-dev \
             ruby-dev \
             sqlite \
             sqlite-dev \
             ttf-dejavu \
             ttf-droid \
             ttf-freefont \
             ttf-liberation \
             tzdata \
             xvfb \
             zlib-dev

      - name: Set up Ruby
        run: bundle install

      - name: Prepare Rails log directory
        run: |
          mkdir -p log
          touch log/test.log
          chmod 0664 log/test.log

      - name: Run RSpec tests
        run: |
          bundle exec rails spec
